dist: trusty
sudo: true
language: c++

addons:
  ssh_known_hosts:
    - gitlab.fi.muni.cz

install:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.6.0/z3-4.6.0-x64-ubuntu-14.04.zip
  - unzip -q z3-4.6.0-x64-ubuntu-14.04.zip -d z3_downloaded
  - sudo cp z3_downloaded/z3-4.6.0-x64-ubuntu-14.04/bin/libz3.{a,so} /usr/lib/
  - wget ftp://vlsi.colorado.edu/pub/cudd-3.0.0.tar.gz
  - tar -xzf cudd-3.0.0.tar.gz
  - cd cudd-3.0.0/
  - ./configure --enable-silent-rules --enable-obj --enable-shared && make && sudo make install

script:
  - mkdir build && cd build && cmake ..
  - cmake --build .
