dist: xenial
sudo: true
language: c++

addons:
  ssh_known_hosts:
    - gitlab.fi.muni.cz
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ggcov
      - autotools-dev
      - automake

notifications:
  email:
    - martin.jonas@mail.muni.cz

before_install:
  - eval "${SET_GCC}"
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  - pip install --user cpp-coveralls

install:
  - export CXX=g++-7
  - export CC=gcc-7
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip
  - unzip -q z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip -d z3_downloaded
  - sudo cp z3_downloaded/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04/bin/libz3.{a,so} /usr/lib/
  - sudo cp z3_downloaded/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04/include/* /usr/include/
  - git clone https://github.com/martinjonas/cudd.git
  - cd cudd
  - ./configure --enable-silent-rules --enable-obj --enable-shared && make -j4 && sudo make install
  - cd ..
  - sudo wget https://www.antlr.org/download/antlr-4.7.2-complete.jar -P /usr/share/java

script:
  - mkdir build && cd build && cmake .. -DCOVERAGE=1 -DANTLR_EXECUTABLE=/usr/share/java/antlr-4.7.2-complete.jar
  - make -j4
  - make test
  - cd ..

after_success:
  - coveralls --exclude app --exclude cudd --exclude z3_downloaded --exclude build --exclude tests --gcov-options '\-lp'